/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basededatos;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.tika.*;
import org.apache.tika.exception.TikaException;
import org.xml.sax.SAXException;

/**
 *
 * @author María Arango
 */
public class CreateOrg extends BaseDeDatos {
    private static String user;
    private String path;
    private File PDF;
    
    /**
     * Creates new form CreateOrg
     */
    public CreateOrg(String user) {
        initComponents();
        this.user = user;
        bCargar.setVisible(false);
        jshowStatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bPath = new javax.swing.JButton();
        bCargar = new javax.swing.JButton();
        this.setVisible(false);
        enterprise = new javax.swing.JComboBox<>();
        getBack = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jshowStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione PDF de la factura");

        jStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jStatus.setForeground(new java.awt.Color(0, 0, 204));
        jStatus.setText("Estado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ingreso de datos de facturación");

        bPath.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bPath.setText("Seleccionar");
        bPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPathActionPerformed(evt);
            }
        });

        bCargar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bCargar.setText("Cargar");
        bCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCargarActionPerformed(evt);
            }
        });

        enterprise.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        enterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la empresa", "EPM", "UNE" }));

        getBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getBack.setText("Regresar");
        getBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBackActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        search.setText("Consultar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jshowStatus.setBackground(new java.awt.Color(0, 0, 0));
        jshowStatus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jshowStatus.setForeground(new java.awt.Color(0, 153, 51));
        jshowStatus.setText("Carga terminada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(getBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(search))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(bPath))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(enterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(bCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jshowStatus)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jStatus)
                    .addComponent(enterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(bPath)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCargar)
                    .addComponent(jshowStatus))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getBack)
                    .addComponent(search))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPathActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            PDF = selectedFile;
            String name = selectedFile.getName();
            path = selectedFile.getAbsolutePath();
           if(name.substring(name.length()-4,name.length()).equals(".pdf")){
               jStatus.setForeground(Color.BLUE);
               bCargar.setVisible(true);
               jStatus.setText(name);
           }
           else{
               jStatus.setForeground(Color.RED);
               jStatus.setText("Archivo seleccionado no es PDF");
           }
        }
    }//GEN-LAST:event_bPathActionPerformed

    private void bCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCargarActionPerformed
        if(enterprise.getSelectedIndex() != 0) {
            int empresaActual;
            if(enterprise.getSelectedIndex() == 1) {
                //Uno para EPM
                empresaActual = 1;
            } else {
                //Dos para UNE
                empresaActual = 2;
            }
        
            try{
            // Aqui se hace la lectura de PDF
            Reader lectura = new Reader(PDF);
            // se manda el read par
            LoadPDFMysql loader = new LoadPDFMysql(lectura, empresaActual, user);
       
            //Cargal a informacion a Mysql
            loader.go();
            //se muestra label de terminado
            jshowStatus.setVisible(true);
            }
            catch(IOException | TikaException | SAXException e){ // mostrar dialogo de realizado o no realizado
            
            }
        } else {
            JOptionPane.showMessageDialog(null,
                "Debe seleccionar la empresa a la cual pertenece su factura.",
                "Error Message",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bCargarActionPerformed

    private void getBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBackActionPerformed
        this.setVisible(false);
        CentroOrg co = new CentroOrg(user);
        co.setVisible(true);
    }//GEN-LAST:event_getBackActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        this.setVisible(false);
        ReadOrg co = new ReadOrg(user);
        co.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrg(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCargar;
    private javax.swing.JButton bPath;
    private javax.swing.JComboBox<String> enterprise;
    private javax.swing.JButton getBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jshowStatus;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
